//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InitialProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InitialProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation browser.
        /// </summary>
        internal static string AccommodationBrowser {
            get {
                return ResourceManager.GetString("AccommodationBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation type: .
        /// </summary>
        internal static string AccommodationType_ {
            get {
                return ResourceManager.GetString("AccommodationType:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional comment:.
        /// </summary>
        internal static string AdditionalComment_ {
            get {
                return ResourceManager.GetString("AdditionalComment:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All forums.
        /// </summary>
        internal static string AllForums {
            get {
                return ResourceManager.GetString("AllForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anywhere/anytime.
        /// </summary>
        internal static string AnywhereAnytime {
            get {
                return ResourceManager.GetString("AnywhereAnytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        internal static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average rating.
        /// </summary>
        internal static string AverageRating {
            get {
                return ResourceManager.GetString("AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel reservation.
        /// </summary>
        internal static string CancelReservation {
            get {
                return ResourceManager.GetString("CancelReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout owner comment.
        /// </summary>
        internal static string CheckoutOwnerComment {
            get {
                return ResourceManager.GetString("CheckoutOwnerComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout rating details.
        /// </summary>
        internal static string CheckoutRatingDetails {
            get {
                return ResourceManager.GetString("CheckoutRatingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose desired date range:.
        /// </summary>
        internal static string ChooseDateRange_ {
            get {
                return ResourceManager.GetString("ChooseDateRange:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close forum.
        /// </summary>
        internal static string CloseForum {
            get {
                return ResourceManager.GetString("CloseForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication:.
        /// </summary>
        internal static string Communication_ {
            get {
                return ResourceManager.GetString("Communication:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cottage.
        /// </summary>
        internal static string Cottage {
            get {
                return ResourceManager.GetString("Cottage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new profile.
        /// </summary>
        internal static string CreateNewProfile {
            get {
                return ResourceManager.GetString("CreateNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string days {
            get {
                return ResourceManager.GetString("days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days:.
        /// </summary>
        internal static string DaysCount_ {
            get {
                return ResourceManager.GetString("DaysCount:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more days to.
        /// </summary>
        internal static string daysTo {
            get {
                return ResourceManager.GetString("daysTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earliest check in:.
        /// </summary>
        internal static string EarliestCheckIn_ {
            get {
                return ResourceManager.GetString("EarliestCheckIn:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter guest count:  .
        /// </summary>
        internal static string EnterGuestCount_ {
            get {
                return ResourceManager.GetString("EnterGuestCount:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything.
        /// </summary>
        internal static string Everything {
            get {
                return ResourceManager.GetString("Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fairness:.
        /// </summary>
        internal static string Fairness_ {
            get {
                return ResourceManager.GetString("Fairness:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find available dates.
        /// </summary>
        internal static string FindAvailableDates {
            get {
                return ResourceManager.GetString("FindAvailableDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten your password?.
        /// </summary>
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forums.
        /// </summary>
        internal static string Forums {
            get {
                return ResourceManager.GetString("Forums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest count: .
        /// </summary>
        internal static string GuestCount_ {
            get {
                return ResourceManager.GetString("GuestCount:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to House.
        /// </summary>
        internal static string House {
            get {
                return ResourceManager.GetString("House", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hygiene:.
        /// </summary>
        internal static string Hygiene_ {
            get {
                return ResourceManager.GetString("Hygiene:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest check out:.
        /// </summary>
        internal static string LatestCheckOut_ {
            get {
                return ResourceManager.GetString("LatestCheckOut:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest comment.
        /// </summary>
        internal static string LatestComment {
            get {
                return ResourceManager.GetString("LatestComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave one or more accommodation images:.
        /// </summary>
        internal static string LeaveAccommodationImages_ {
            get {
                return ResourceManager.GetString("LeaveAccommodationImages:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string Location_ {
            get {
                return ResourceManager.GetString("Location:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string LocationSort {
            get {
                return ResourceManager.GetString("LocationSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max guests:.
        /// </summary>
        internal static string MaxGuests_ {
            get {
                return ResourceManager.GetString("MaxGuests:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum guest count ↘.
        /// </summary>
        internal static string MaxGuestSortD {
            get {
                return ResourceManager.GetString("MaxGuestSortD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum guest count↗.
        /// </summary>
        internal static string MaxGuestSortU {
            get {
                return ResourceManager.GetString("MaxGuestSortU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum guests: .
        /// </summary>
        internal static string MaximumGuests_ {
            get {
                return ResourceManager.GetString("MaximumGuests:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min days:.
        /// </summary>
        internal static string MinDays_ {
            get {
                return ResourceManager.GetString("MinDays:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum days number ↘.
        /// </summary>
        internal static string MinDaysSortD {
            get {
                return ResourceManager.GetString("MinDaysSortD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum days number ↗.
        /// </summary>
        internal static string MinDaysSortU {
            get {
                return ResourceManager.GetString("MinDaysSortU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum cancelation notice: .
        /// </summary>
        internal static string MinimumCancelationNotification_ {
            get {
                return ResourceManager.GetString("MinimumCancelationNotification:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum days: .
        /// </summary>
        internal static string MinimumDays_ {
            get {
                return ResourceManager.GetString("MinimumDays:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move reservation.
        /// </summary>
        internal static string MoveReservation {
            get {
                return ResourceManager.GetString("MoveReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My forums.
        /// </summary>
        internal static string MyForums {
            get {
                return ResourceManager.GetString("MyForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My info.
        /// </summary>
        internal static string MyInfo {
            get {
                return ResourceManager.GetString("MyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reservations.
        /// </summary>
        internal static string MyReservations {
            get {
                return ResourceManager.GetString("MyReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameSort {
            get {
                return ResourceManager.GetString("NameSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unread notifications .
        /// </summary>
        internal static string NewNotifications {
            get {
                return ResourceManager.GetString("NewNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise level:.
        /// </summary>
        internal static string NoiseLevel_ {
            get {
                return ResourceManager.GetString("NoiseLevel:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existing ratings for this accommodation.
        /// </summary>
        internal static string NoRatingsAccommodation {
            get {
                return ResourceManager.GetString("NoRatingsAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existing ratings for this owner.
        /// </summary>
        internal static string NoRatingsOwner {
            get {
                return ResourceManager.GetString("NoRatingsOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Not required).
        /// </summary>
        internal static string NotRequired {
            get {
                return ResourceManager.GetString("NotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall experience:.
        /// </summary>
        internal static string OverallExperience_ {
            get {
                return ResourceManager.GetString("OverallExperience:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner: .
        /// </summary>
        internal static string Owner_ {
            get {
                return ResourceManager.GetString("Owner:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking:.
        /// </summary>
        internal static string Parking_ {
            get {
                return ResourceManager.GetString("Parking:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string Password_ {
            get {
                return ResourceManager.GetString("Password:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF documentation about making a reservation.
        /// </summary>
        internal static string PDF {
            get {
                return ResourceManager.GetString("PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending response.
        /// </summary>
        internal static string PendingResponse {
            get {
                return ResourceManager.GetString("PendingResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number: .
        /// </summary>
        internal static string PhoneNumber_ {
            get {
                return ResourceManager.GetString("PhoneNumber:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a rating for each category.
        /// </summary>
        internal static string PickRatingForEachCategory {
            get {
                return ResourceManager.GetString("PickRatingForEachCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleasantness:.
        /// </summary>
        internal static string Pleasantness_ {
            get {
                return ResourceManager.GetString("Pleasantness:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post comment.
        /// </summary>
        internal static string PostComment {
            get {
                return ResourceManager.GetString("PostComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate accommodation.
        /// </summary>
        internal static string RateAccommodation {
            get {
                return ResourceManager.GetString("RateAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rate this accommodation.
        /// </summary>
        internal static string rateThisAccommodation {
            get {
                return ResourceManager.GetString("rateThisAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rating: .
        /// </summary>
        internal static string rating_s {
            get {
                return ResourceManager.GetString("rating:s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        internal static string Ratings {
            get {
                return ResourceManager.GetString("Ratings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received ratings.
        /// </summary>
        internal static string ReceivedRatings {
            get {
                return ResourceManager.GetString("ReceivedRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renovating needed:.
        /// </summary>
        internal static string RenovatingNeeded_ {
            get {
                return ResourceManager.GetString("RenovatingNeeded:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This comment has been reported as invalid. Number of reports: .
        /// </summary>
        internal static string ReportedComment {
            get {
                return ResourceManager.GetString("ReportedComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request accepted.
        /// </summary>
        internal static string RequestAccepted {
            get {
                return ResourceManager.GetString("RequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request denied.
        /// </summary>
        internal static string RequestDenied {
            get {
                return ResourceManager.GetString("RequestDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make a reservation.
        /// </summary>
        internal static string Reserve {
            get {
                return ResourceManager.GetString("Reserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respects rules:.
        /// </summary>
        internal static string RespectsRules_ {
            get {
                return ResourceManager.GetString("RespectsRules:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  days.
        /// </summary>
        internal static string sDays {
            get {
                return ResourceManager.GetString("sDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a request.
        /// </summary>
        internal static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent requests.
        /// </summary>
        internal static string SentRequests {
            get {
                return ResourceManager.GetString("SentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  guests,.
        /// </summary>
        internal static string sGuestsComma {
            get {
                return ResourceManager.GetString("sGuestsComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all comments.
        /// </summary>
        internal static string ShowAllComments {
            get {
                return ResourceManager.GetString("ShowAllComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by:.
        /// </summary>
        internal static string SortBy_ {
            get {
                return ResourceManager.GetString("SortBy:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start forum.
        /// </summary>
        internal static string StartForum {
            get {
                return ResourceManager.GetString("StartForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Required) Starting comment/question....
        /// </summary>
        internal static string StartingQuestion {
            get {
                return ResourceManager.GetString("StartingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start new forum.
        /// </summary>
        internal static string StartNewForum {
            get {
                return ResourceManager.GetString("StartNewForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit rating.
        /// </summary>
        internal static string SubmitRating {
            get {
                return ResourceManager.GetString("SubmitRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super owner.
        /// </summary>
        internal static string SuperOwner {
            get {
                return ResourceManager.GetString("SuperOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeliness:.
        /// </summary>
        internal static string Timeliness_ {
            get {
                return ResourceManager.GetString("Timeliness:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic.
        /// </summary>
        internal static string Topic {
            get {
                return ResourceManager.GetString("Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topic:.
        /// </summary>
        internal static string Topic_ {
            get {
                return ResourceManager.GetString("Topic:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrated accommodations.
        /// </summary>
        internal static string UnratedAccommodations {
            get {
                return ResourceManager.GetString("UnratedAccommodations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urgency level:.
        /// </summary>
        internal static string UrgencyLevel_ {
            get {
                return ResourceManager.GetString("UrgencyLevel:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string Username_ {
            get {
                return ResourceManager.GetString("Username:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User owns an accommodation on this location.
        /// </summary>
        internal static string UserOwnsAccommodation {
            get {
                return ResourceManager.GetString("UserOwnsAccommodation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has visited this location.
        /// </summary>
        internal static string UserVisitedLocation {
            get {
                return ResourceManager.GetString("UserVisitedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very useful.
        /// </summary>
        internal static string VeryUseful {
            get {
                return ResourceManager.GetString("VeryUseful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What needs renovating:.
        /// </summary>
        internal static string WhatNeedsRenovating_ {
            get {
                return ResourceManager.GetString("WhatNeedsRenovating:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have .
        /// </summary>
        internal static string YouHave {
            get {
                return ResourceManager.GetString("YouHave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your coment....
        /// </summary>
        internal static string YourComent {
            get {
                return ResourceManager.GetString("YourComent", resourceCulture);
            }
        }
    }
}
